### ISSUE TITLE
update banner and logos

### ISSUE THREAD

**Issue by kwcooper** [GCCR/GCCR.github.io#12]
I'll do this, just keeping it here so I remember.

**Comment by kwcooper** [comment]
Just waiting on some more images and then I can push this

**Comment by cbouy** [comment]
@kwcooper I've already added this logo ![assets/img/logo_draft_white.jpg](https://github.com/GCCR/GCCR.github.io/blob/master/assets/img/logo_draft_white.jpg?raw=true) (in assets/img/logo_draft_white.jpg) as the twitter summary card (the image shown on a tweet when someones shares the link to gcchemosensr.org). If you find another image to be more approriate, you can change this in the _config.yml file:
https://github.com/GCCR/GCCR.github.io/blob/979b5423c7f928c87280944ccc778f1e4162ce95/_config.yml#L21

**Comment by mariaveldhuizen** [comment]
Can we try this banner?  Let me know if the fade needs to fade further to the left of the image if you want to keep a similar crop on the banner? 
![banner_adjustments_fade](https://user-images.githubusercontent.com/41241688/80986141-d28d2680-8e38-11ea-8b6e-f5cd3bde8694.png)

**Comment by mariaveldhuizen** [comment]
Change the GCCR home text in the top left of the banner to the “logo”, and make it bigger.  I have a black and a white version with transparent background with the exact same dimensions, so you can change color when capturing mouse. If you want I can also give grey or dark green if that looks better. 
![logo_draft_logo_white](https://user-images.githubusercontent.com/41241688/80986439-3c0d3500-8e39-11ea-8d43-ce0a8823af96.png)
![logo_draft_logo_black](https://user-images.githubusercontent.com/41241688/80986442-3ca5cb80-8e39-11ea-8866-9998c61bf8a4.png)

**Comment by mariaveldhuizen** [comment]
On the right side of the banner we want our full name, but also a subheading sentence with words that are search engine optimized. “Scientists, clinicians and patient advocates conducting international studies on taste and smell.” With the faded banner this should be possible now. Probably in a dark grey colour. I would recommend verdana for the font.

**Comment by cbouy** [comment]
oops wrong issue reference, please ignore it!

**Comment by kwcooper** [comment]
We may soon want to start thinking about re-branding away from COVID-19 imagery, (at the least) to grow GCCR beyond it's COVID-19 roots. (Instead of a giant virus in the header, perhaps someone smelling, or eating or... sky's the limit). When / if this happens, we can make some of the other more aesthetic changes.  Any thought's @mariaveldhuizen or @cbouy ?

**Comment by cbouy** [comment]
I agree on this one, less big scary virus would be better 😄

**Comment by kwcooper** [comment]
#[2dd25e6](https://github.com/GCCR/GCCR.github.io/commit/2dd25e69f5f17c65086d2ce3e38231292c30f975) closes (thanks all!)
