### ISSUE TITLE
request to embed/host video

### ISSUE THREAD

**Issue by mariaveldhuizen** [GCCR/GCCR.github.io#17]
We are going to get a video that we want to have on the web page. I think hosting on youtube and embedding on the page is the way to go, agree? Just a heads up that we will be looking to embed that at some point.

**Comment by cbouy** [comment]
Yes youtube is the simplest option, and it's easy to embed on the website

**Comment by kwcooper** [comment]
+1 to what Cedric said. Send me the link and I can add. We may want to be mindful of possible geographic restrictions though should they arise

**Comment by kwcooper** [comment]
@mariaveldhuizen any updates on the video?

**Comment by kwcooper** [comment]
After the conversation today I think we got this
