### ISSUE TITLE
created by... 

### ISSUE THREAD

**Issue by mariaveldhuizen** [GCCR/GCCR.github.io#18]
In the footer it should say who created the page and when. It's right to be acknowledged!

**Comment by kwcooper** [comment]
I like the idea, especially when the page was updated and who did it to keep track. 

That said... Which pages? All of them? I fear it may be difficult to assign credit (ie. people are working on different aspects of the main page, back-end work vs content). If we begin to have more and more pages this will be more applicable IMO, especially when we have a blog or pages that are continually updated. We'll have to think about this, any suggestions? 

We could think of adding something similar to the members page? Or add a more formal hierarchy not only to the website but GCCR in general... I like how the LA Times handles this: https://www.latimes.com/newsroom-directory

**Comment by cbouy** [comment]
I agree with Keiland for most pages it's going to be difficult to say who is the author. But adding a page where we specify the role of each members would be great.
For blog posts the logic of specifying the author is already there.

**Comment by kwcooper** [comment]
FYI, I started putting my initials as a comment on some of the pages. Github commits will track who makes updates. 
As the site grows however, the footer idea may make more sense, as to which we can re-open this or make a new issue.
