### ISSUE TITLE
some new links to other tools

### ISSUE THREAD

**Issue by mariaveldhuizen** [GCCR/GCCR.github.io#19]
Lyon Neuroscience Research Center website and questionnaire on quality of life and olfactory disorders (in French) 
"website" linked to https://project.crnl.fr/odorat-info/, "quality of life and olfactory disorders" linked to https://form.crnl.fr/index.php/146862?newtest=Y&lang=fr

Can we also take the (GCCR) behind Noam Sobel's name out?

**Comment by cbouy** [comment]
Done !
