### ISSUE TITLE
Improvement suggestion: social network links for sharing

### ISSUE THREAD

**Issue by Huitzilo** [GCCR/GCCR.github.io#20]
I wonder whether it might be worthwhile replacing the "share survey" links by buttons for facebook, twitter, and a link?

**Comment by cbouy** [comment]
You mean displaying the social buttons directly instead of having to click on "share survey" ?

**Comment by Huitzilo** [comment]
yeah, why not - this would make the available options obvious, without having to click a button that the user doesn't know where it leads.

**Comment by cbouy** [comment]
I made the change and I added the social buttons on the landing page as well

**Comment by kwcooper** [comment]
I like this a lot!
