### ISSUE TITLE
COVID-19 projects page:

### ISSUE THREAD

**Issue by mariaveldhuizen** [GCCR/GCCR.github.io#21]
Please remove the literature section, it is hopelessly outdated (already) and it’s probably too much work to keep up.Let’s just  refer to Pellegrino preprint and to the page that was created specifically for COVID-19 related research:  https://www.ncbi.nlm.nih.gov/research/coronavirus/

**Comment by cbouy** [comment]
We should also add the medRxiv preprint of GCCR001 when it's available online

**Comment by kwcooper** [comment]
done.
