### ISSUE TITLE
Members

### ISSUE THREAD

**Issue by mariaveldhuizen** [GCCR/GCCR.github.io#22]
Can we get the members alphabetically sorted by last name and/or by country?

**Comment by cbouy** [comment]
The membership form only had a "Full name" field which was not necessarily filled in the "first name last name" order by members. So I can't order specifically by last name, only by full name.
Should I sort by country, then by full name ? Or keep as it is now (sorted by full name) ?

I could also add an interactive (sortable and searchable) table if necessary

**Comment by mariaveldhuizen** [comment]
How about I parse the names, then we can do it :)

Sent from my iPhone

On May 6, 2020, at 17:48, Cédric Bouysset <notifications@github.com> wrote:

﻿

The membership form only had a "Full name" field which was not necessarily filled in the "first name last name" order by members. So I can't order specifically by last name, only by full name.
Should I sort by country, then by full name ? Or keep as it is now (sorted by full name) ?

I could also add an interactive (sortable and searchable) table if necessary

**Comment by cbouy** [comment]
Good luck with the 400+ rows to parse 😆
