### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by mariaveldhuizen** [GCCR/GCCR.github.io#24]
I think that we are ready for a blog page where we can put small blurbs on GCCR and GCCR member outputs, like published papers, preprint, etc

**Comment by cbouy** [comment]
The website is ready for this, we just need some content, either directly in markdown, or in a docx file.
Related to issue #9

**Comment by mariaveldhuizen** [comment]
Great, let me get some content and can it be in GCCR contact google drive?

**Comment by cbouy** [comment]
Sure ! Just notify me when you're done

**Comment by kwcooper** [comment]
@mariaveldhuizen did you ever get a chance to add content for the blog?

**Comment by mariaveldhuizen** [comment]
Not yet, and I doubt I'll get around to it, but I'm going to find some folks for it.

**Comment by kwcooper** [comment]
It would be really cool to have a blog up and running, if we can find volunteers. Please let me know if there's any renewed interest in this @mariaveldhuizen, but for now I'll close this.
