### ISSUE TITLE
Sitemap automatic lastmod

### ISSUE THREAD

**Issue by cbouy** [GCCR/GCCR.github.io#25]
Goal:
Automatically update the sitemap's `lastmod` field for each page when it's actually updated.

From what I see, it's not possible with github-pages (there's a plugin but it's not whitelisted by github so we cannot install it).
There seem to be an interesting answer here though, by setting a git pre-commit hook (never used those tbh): https://stackoverflow.com/a/33721446.
I'll check if it's doable

**Comment by kwcooper** [comment]
If you're taking this as a personal challenge then it would be super cool if a solution could be haked together, but please don't stess over it. 
The precommit hook thread seems interesting, but I wonder if it will interfere with anything else? Is this the plugin you're talking about? https://github.com/jekyll/jekyll-sitemap

**Comment by cbouy** [comment]
No this plugin is already installed but doesn't put any lastmod or priority field, that's why I had to switch to manually adding the sitemap file. The plugin is https://github.com/gjtorikian/jekyll-last-modified-at
