### ISSUE TITLE
we now have slack invitation link that does not expire - for our welcome message

### ISSUE THREAD

**Issue by tristramw-uk** [GCCR/GCCR.github.io#26]
I've managed to create a slack invitation link which does not expire.  Do use in our welcome/invitation message

https://join.slack.com/t/gccr-mql6351/shared_invite/zt-ebcwcjuc-hxq1KLa7b9V3ewJi1YyFNw

using advice from a reddit message 
https://www.reddit.com/r/Slack/comments/e26mn8/automating_slack_invites/

**Comment by kwcooper** [comment]
This is great. But do we have a public link to slack? I was under the impression that this was sent after people inquired about becoming a member.  Though I may be wrong.

**Comment by tristramw-uk** [comment]
thanks K. Having a non-expiring link just means that the message sent to people enquiring about becoming a member does not need to be updated with a new link every 2 weeks.
