### ISSUE TITLE
Github security complaints

### ISSUE THREAD

**Issue by kwcooper** [GCCR/GCCR.github.io#5]
@cbouy Do you see that Github is warning us about a security issue?
If so, do you have any idea what this might be? 

If not, I'll look into it!

Thank you!

**Comment by cbouy** [comment]
I don't see them, I think you need to give me write access to this repo in the settings. You might have to create a team for that.

**Comment by kwcooper** [comment]
I think I fixed it. Stay tuned. Curious you can't see it though, you should have full privileges for that repo..?
