### ISSUE TITLE
Failed builds?

### ISSUE THREAD

**Issue by kwcooper** [GCCR/GCCR.github.io#65]
@cbouy Hi! Do you have any ideas on why our build keeps failing? I think it has to do with the gem / ruby versions, but things seemed okay when I looked through them

**Comment by cbouy** [comment]
Hey @kwcooper! Is there a reason why we have [3 different build workflows](https://github.com/GCCR/GCCR.github.io/actions)?

AFAIK the "Build and deploy Jekyll site to GitHub Pages" is the one that I setup to run our custom Python scripts for generating the members map and so on, so it's probably the one we need to keep.

**Comment by kwcooper** [comment]
No clue. I had to fix a broken python package once in the workflow, maybe I accidentally duplicated it. Would you mind removing all but yours? 

I don't think that will fix the ruby issues though

**Comment by cbouy** [comment]
No worries I'll investigate and try to freshen the dependencies up a bit so hopefully we don't have to merge those security updates every week

**Comment by kwcooper** [comment]
Awesome! Thank you! Please let me know if there's anything I can do on my end!

**Comment by kwcooper** [comment]
@cbouy it didn't quite work... an issue with the environment, see the failed build in actions. 

`Failed to execute ["bash","-c","micromamba create -n gccr --strict-channel-priority -y -f /home/runner/work/GCCR.github.io/GCCR.github.io/_scripts/environment.yml"]`

**Comment by cbouy** [comment]
Looks like I was a bit too strict on dependencies, I made some changes which fixed the environment but now there seem to be another error in the scripts themselves (and it's a weird one)... I'll have a closer look tomorrow

**Comment by cbouy** [comment]
Fixed!

**Comment by kwcooper** [comment]
Thanks!

**Comment by cbouy** [comment]
I'll try to have a look this weekend
