### ISSUE TITLE
Scripts to update the member's list and map

### ISSUE THREAD

**Issue by cbouy** [GCCR/GCCR.github.io#7]
Currently, the map is read from another [repo](https://github.com/GCCR/members-map), and for the list of members I did a quick regex on the [listOMems.html](https://github.com/GCCR/GCCR.github.io/blob/master/listOMems.html) to convert it to the YAML format in [_data/members.yml](https://github.com/GCCR/GCCR.github.io/blob/dev/_data/members.yml). Both map and list are generated from the same excel sheet.

I suggest adding a `_scripts` folder with a python script that will update both the map and the list. The output files should directly go to _includes for the map, and _data for the list. I'll also add my conda environment in a file so that everyone who has access to the excel file can run the update.

**Comment by mariaveldhuizen** [comment]
If i can make this process easier let me know. I'm new to github, but I need to learn.

**Comment by kwcooper** [comment]
So I used a python script to generate the original member's list file (I hope you don't think that I typed that... ) 

In short it takes the members excel, strips the people, and spits out the formatted table of members. I can upload it as a starting point. 

@cbouy will then have to then further modify it to fit whatever formatting his map needs. I doubt this will take much work, though I am naive to exactly what his map needs.

**Comment by kwcooper** [comment]
... annnnd done: https://github.com/GCCR/GCCR.github.io/blob/master/scripts/parse_mems.py#L1

I was in a rush, so it's just the bare minimum. I just had it build a txt file of the members. My dream was to have it build the whole file mems.html, which again really wouldn't be too hard, but I was in a rush trying to do other things that day. 

It should speak for itself, but as always, happy to answer any questions!

**Comment by cbouy** [comment]
checklist for me:
- [x] capitalize members names automatically
- [x] add conda environment (already in the map repo)
- [x] add instructions on how to install the dependencies and run the script
- [x] make debugging common problems easier (and log duplicated entries and empty rows)
- [x] output number of members, number of countries
- [x] add the map generation script
- [x] add the members list YML generator

**Comment by cbouy** [comment]
Script updated in the dev branch (with instructions): [https://github.com/GCCR/GCCR.github.io/tree/dev/_scripts](https://github.com/GCCR/GCCR.github.io/tree/dev/_scripts)
I'll close the issue.
