### ISSUE TITLE
News posts

### ISSUE THREAD

**Issue by cbouy** [GCCR/GCCR.github.io#9]
I'm planning to implement [Publii](https://getpublii.com/) support to the website so that people can easily write posts without having to learn how markdown works, understand the structure of the website, where to put images...etc. 

Their are also a few other improvements to make (code suggestions [here](https://blog.webjeda.com/jekyll-categories/)):
- add the ability to assign categories/tags to each post (covid-19, taste, smell, ...etc.)
- suggest 2-3 recent posts of the same category at the bottom of each post
- add a page listing all posts by category (and link to each category at the top)
- comment section ?

**Comment by kwcooper** [comment]
I like all of these. I'll teach myself Publii after we move to Jekyll and help out with these.

**Comment by kwcooper** [comment]
Now that Jekyll is sailing so smoothly (I'm kicking myself for not doing this earlier, thanks again and again Cbouy), where are we will Publii integration for blog posts (especially if we hit a wave of press coverage?)
Anything you need my help with?

**Comment by cbouy** [comment]
I tried it 2 days ago but didn't manage to connect it with my github account, I need to contact them about that. Also I'm not sure if we can use this only for blogposts and keep our own website theme. After installation, it looks like publii can only be used to build a website from scratch, I'm not sure if we can implement it on an already existing website... I'll get in touch with them and keep you informed.

**Comment by kwcooper** [comment]
Any news on news? I think it may be all the well if we just start with adding the markdown posts, as per the ease of Jekyll's interface, and resort to publii or an alternative should manually adding them get out of hand.

 In the code it seems that you have the blog post templates set up already, can we start sourcing them and add a new page to the website, or do you think there needs to be more work on the back end to the the template-ing code ready for production?

**Comment by cbouy** [comment]
Yes, so we can use Publii for the blog section only, but they didn't give me directions on how to do so. I'll try but definitely not a priority. As you say, we can do it by hand for now, there's even a [docx to markdown converter](https://word2md.com/) to make it easier !
We can already use the news section, everything is ready [https://gcchemosensr.org/news/](https://gcchemosensr.org/news/). Just so you know, if you want to add an author, it's in _data/authors.yml. For now there's you, me and the default "GCCR". If the `author` frontmatter of a post isn't found in the authors file, it will use the twitter handle and avatar of the "GCCR" author.
There's a dummy post that I made in `_posts` just to test the logic which should be replaced by the post D. Reed made a while back on the google doc for the website. Once it's ready I'll make it visible on the sitemap.
The improvements that I listed in my first post will be useful when we have enough posts, but for now it's fine.

**Comment by kwcooper** [comment]
This is great @cbouy ! @mariaveldhuizen would you mind asking leadership for some news posts to add (even past ones, maybe going through the GCCR twitter) to populate the page? This way people can see the old stuff that we've been up to too. 

Also, when we tweet future news, we can link them to the news posts for the "full story" and drive more traffic.

**Comment by kwcooper** [comment]
This can be handled by a previous issue
